### ISSUE TITLE
RealBin

### ISSUE THREAD

**Issue by har-wradim** [mptrsen/Orthograph#22]
I would suggest to universally replace `use lib $FindBin::Bin` with `use lib $FindBin::RealBin` in the scripts, because otherwise one gets in trouble when using soft links.

**Comment by mptrsen** [comment]
Thanks for your suggestion! Will do that.

M

Once upon a time (Fri, 20 May 2016 06:50:40 -0700), Andrey Rozenberg 
<notifications@github.com> said:

**Comment by har-wradim** [comment]
Seems to be fixed in [release 0.5.14](https://github.com/mptrsen/Orthograph/tree/0.5.14).
