### ISSUE TITLE
Issue with swipe.pm

### ISSUE THREAD

**Issue by zjlahey** [mptrsen/Orthograph#25]
$ ./orthograph-analyzer --test-deps
Experimental splice on scalar is now forbidden at ~/Orthograph/Wrapper/Swipe.pm line 305, near "4;"
Compilation failed in require at ./orthograph-analyzer line 44.
BEGIN failed--compilation aborted at ./orthograph-analyzer line 44.

**Comment by mptrsen** [comment]
Thanks for reporting. Fixed.
