### ISSUE TITLE
Permission/path for swipe?

### ISSUE THREAD

**Issue by zjlahey** [mptrsen/Orthograph#26]
Running as sudo does not fix the issue. Thanks for you help - I'm looking forward to getting this program running!

$ ./orthograph-analyzer --test-deps
Parsing config file '/Orthograph/orthograph.conf'.
Using SQLite database file 'test_data/test_set.sqlite'
Using SQLite database file 'test_data/output/Orussus_abietinus/Orussus_abietinus.sqlite' as species-specific database
Fatal: SWIPE not executable at 'swipe'. Verify path and/or permissions.

**Comment by mptrsen** [comment]
The path to the 'swipe' executable needs to be specified as `swipe-program` if
it is not installed in `$PATH`.

Once upon a time (Mon 2017-02-06 08:58), zjlahey said:
