### ISSUE TITLE
ForkManager eludes the test

### ISSUE THREAD

**Issue by nylander** [mptrsen/Orthograph#27]
Hi Malte!

I'm trying out the orthograph package on a (Ubuntu 16.10) Linux system without Parallel::ForkManager, but it gives an error way passed the test for ForkManager's presence:

    ./orthograph-analyzer --test-deps && ./orthograph-analyzer
    ...some progress printing...
    Can't locate object method "new" via package "Parallel::ForkManager" at ./orthograph-analyzer line 450.

I see you have a code at line 244 in orthograph-analyzer, so I was surprised to see my run start and proceed all the way to 450. No clue why at the moment, so just as a heads-up.

Cheers
Johan

**Comment by mptrsen** [comment]
Thanks for the heads up. I added another test to catch this error earlier and give a more meaningful message.
