### ISSUE TITLE
Can't locate object method "new"

### ISSUE THREAD

**Issue by Arctictern6** [mptrsen/Orthograph#30]
when I test the software,the following error showed:
Can't locate object method "new" via package "Parallel::ForkManager" at ./orthograph-analyzer line 457.

Could you help me solve it?
Thank you

**Comment by mptrsen** [comment]
Please make sure you have the Perl module Parallel::ForkManager installed. You can get it [from CPAN](https://metacpan.org/pod/Parallel::ForkManager).

Let me know if that doesn't solve the problem.

**Comment by Arctictern6** [comment]
Indeed, there is no Perl module Parallel::ForkManager in my computer,I have solved it. Thank you very much.

And I have another question now:
When I proceeded the step 4:Load OGS sequences into the database 
I have loaded a wrong OGS sequences ,and the name is also wrong.
so how should I delete it?
I will be grateful if you could hep me with that.

**Comment by Arctictern6** [comment]
Indeed, there is no Perl module Parallel::ForkManager in my computer,I have solved it. Thank you very much.
And I have another question now:
When I proceeded the last step,it showed that:

Backing up old output files...
Old output files backed up in 'test_data/output/Orussus_abietinus/backup-2018-06-29_19:26.tar.bz2' (23 files).
Redundant argument in printf at ./orthograph-analyzer line 847.
Fatal: Set 'test_set' does not exist in database 'orthograph'. Typo in config file /home/bio/Transcriptome/Orthograph-0.6.3/orthograph.conf? Use orthograph-manager first to set up your ortholog sets. Ask your administrator.

**Comment by mptrsen** [comment]
Please stop editing your comments to ask new questions every hour. I am now closing this issue as the original problem has been resolved. For different problems, please open a new issue if you think it might be a bug. Otherwise, please write me an email. Thank you.
