### ISSUE TITLE
Inputting amino acid sequences

### ISSUE THREAD

**Issue by austinv11** [mptrsen/Orthograph#32]
Is it possible to input amino acid sequences instead of transcriptome data? Or should I attempt to reverse translate my amino acid data?

**Comment by mptrsen** [comment]
This is currently not supported, but you should be able to work around it by fooling Orthograph into thinking it already translated the input:

1. Make a copy of your input file, adding `_prot` to the end the filename before the extension. That is, a file named `input.fa` should be copied to `input_prot.fa`.
2. Run Orthograph normally.

Note that the output will likely contain irregularities and the nucleotide sequence output will of course be wrong. I am also not sure if this works completely, so please try it and let me know if it works.

**Comment by austinv11** [comment]
It appears to fail at analysis as taking a look at the analyzer log shows this at the end: 
```
Fatal: Could not translate input file. Is this nucleotide data? 
```

**Comment by mptrsen** [comment]
I added the option `input-is-amino-acid` to allow this. Please try out the [new release 0.7.0](https://github.com/mptrsen/Orthograph/releases/tag/0.7.0) (and sorry for the late response, I hope this is still relevant).
