### ISSUE TITLE
bug? Orthograph cannot use anymore the PARALLEL::ForkManager

### ISSUE THREAD

**Issue by kmeusemann** [mptrsen/Orthograph#35]
Hi there,

I just wanted to rerun in Orthograph  a species, but now get an error and the message:
Wrote 128724 translated sequences to /media/meusemann/32b4a029-7d23-4135-a9ac-83135140bd48/Julia_orthology/Orthograph_results_KM3/O_javanicus_JAPAN_cds/tmp/BMdk
HMMsearching the translated sequences using all 8552 HMMs in /media/meusemann/32b4a029-7d23-4135-a9ac-83135140bd48/Julia_orthology/oryzias/hmms...
Can't locate object method "new" via package "Parallel::ForkManager" at ./orthograph-analyzer line 457.

-> also it cannot use several threads anymore ovbioulsy.

HELP APPRECIATED pls! (using Orthograph 0.6.3...

Karen

**Comment by mptrsen** [comment]
Hi,

please make sure to use the latest Orthograph version. Also, make sure the Perl module Parallel::ForkManager is installed (this is not part of the Orthograph distribution).

**Comment by kmeusemann** [comment]
Thanks Malte,
for the fast reply,

1) now (re-)installed Parallel::ForkManager via cpan and restartet the run. Now I hope it will work. Strange since I did not change since April (back then also using Orthograph 0.6.3) and it did work well. Anyway: 
2) I am still running 0.6.3 for 2 additional taxa - not the latest version - since I ran various taxa with 0.6.3 - to keep it consistent - or are there serious issues/bugs fixed til then so that you recommed to rerun ALL species with the latest version? I checked the release notes, but could not figure out if there are "serious" bugs (to me, it did not seems so

Thanks a lot
Karen

**Comment by mptrsen** [comment]
Hi Karen,

there have been no algorithmic changes since 0.6.3 (only bug fixes and additional features), therefore it would make no difference to re-run all datasets. Stay with 0.6.3 for the rest of the analysis unless you need the new features, but do consider upgrading for any future projects :)

Closing this issue since apparently resolved by installing Parallel::ForkManager via cpan.

**Comment by kmeusemann** [comment]
Great for the fast reply - thanks!!! :))
best, karen
